export  const CoinObj = [
    {
       "one": {"img":'https://assets.coingecko.com/coins/images/15364/small/logo.png?1620647627',
        "id": "catecoin",
        "coin_id": 15364,
        "name": "CateCoin",
        "symbol": "CATE",
        "market_cap_rank": 549,
        "launch": "2/12/20",
        "change": '+1.5%',
        "chain": 'BSC',
        'vote':240,
        'watchlist': false}
    },
    {
      "two":  {"id": "astroswap",
        "coin_id": 18816,
        "name": "AstroSwap",
        "symbol": "ASTRO",
        "market_cap_rank": 696,
        "img": "https://assets.coingecko.com/coins/images/18816/small/astro.png?1633506850",
        "launch": "3/3/21",
        "change": '-0.8%',
        "chain": 'BSC',
        'vote':14050,
        'watchlist': false}
    },
    {
      "three":  {"id": "wonderland",
        "coin_id": 18126,
        "name": "1der",
        "symbol": "TIME",
        "market_cap_rank": 188,
        "img": "https://assets.coingecko.com/coins/images/18126/small/time.PNG?1630621941",
        "launch": "7/3/22",
        "change": '+2.3%',
        "chain": 'ETH',
        'vote':15,
        'watchlist': false}
    },
    {
       "four": {"id": "insure",
        "coin_id": 10354,
        "name": "inSureDeFi",
        "symbol": "SURE",
        "market_cap_rank": 297,
        "img": "https://assets.coingecko.com/coins/images/10354/small/logo-grey-circle.png?1614910406",
        "launch": "3/8/19",
        "change": '+1.9%',
        "chain": 'ETH',
        'vote':772,
        'watchlist': false}
    },
    {
       "five": {"id": "fantom",
        "coin_id": 4001,
        "name": "Fantom",
        "symbol": "FTM",
        "market_cap_rank": 30,
        "img": "https://assets.coingecko.com/coins/images/4001/small/Fantom.png?1558015016",
        "launch": '2/11/19',
        "change": '-0.5%',
        "chain": 'ETH',
        'vote':240,
        'watchlist': false}
    },
    {"six":{
        "id": "telos",
        "coin_id": 7588,
        "name": "Telos",
        "symbol": "TLOS",
        "market_cap_rank": 237,
        "img": "https://assets.coingecko.com/coins/images/7588/small/TLOS_200.png?1629277084",
        "launch": '11/11/21',
        "change": '-1.5%',
        "chain": 'BSC',
        'vote':177,
        'watchlist': false
    }},
    {"seven":{
        "id": "orca",
        "coin_id": 17547,
        "name": "Orca",
        "symbol": "ORCA",
        "market_cap_rank": 577,
        "img": "https://assets.coingecko.com/coins/images/17547/small/Orca_Logo.png?1628781615",
        "launch": '1/3/21',
        "change": '-1.34%',
        "chain": 'ETH',
        'vote':4744439,
        'watchlist': false
    }},
    {"eight":{
        "img":'https://assets.coingecko.com/coins/images/15364/small/logo.png?1620647627',
        "id": "catecoin",
        "coin_id": 15364,
        "name": "KCoin",
        "symbol": "CATE",
        "market_cap_rank": 677,
        "launch": '2/2/23',
        "change": '-0.05%',
        "chain": 'BSC',
        'vote':4,
        'watchlist': false
    }},
    {"nine":{
        "id": "astroswap",
        "coin_id": 18816,
        "name": "Astr0",
        "symbol": "ASTRO",
        "market_cap_rank": 45,
        "img": "https://assets.coingecko.com/coins/images/18816/small/astro.png?1633506850",
        "launch": '3/1/19',
        "change": '+1.94%',
        "chain": 'BSC',
        'vote':240,
        'watchlist': false
    }},
    {"ten":{
        "id": "wonderland",
        "coin_id": 18126,
        "name": "DISNEY",
        "symbol": "Cost",
        "market_cap_rank": 177,
        "img": "https://assets.coingecko.com/coins/images/18126/small/time.PNG?1630621941",
        "launch": '7/11/22',
        "change": '+0.3%',
        "chain": 'BSC',
        'vote':140,
        'watchlist': false
    }},
    {"eleven":{
        "id": "insure",
        "coin_id": 1317,
        "name": "cerTainDeFi",
        "symbol": "cerTaiN",
        "market_cap_rank": 97,
        "img": "https://assets.coingecko.com/coins/images/10354/small/logo-grey-circle.png?1614910406",
        "launch": '3/8/20',
        "change": '-0.35%',
        "chain": 'ETH',
        'vote':240,
        'watchlist': false
    }},
    {"twelve":{
        "id": "fantom",
        "coin_id": 400,
        "name": "Fanadom",
        "symbol": "FTM-TOKEN",
        "market_cap_rank": 300,
        "img": "https://assets.coingecko.com/coins/images/4001/small/Fantom.png?1558015016",
        "launch": '2/7/22',
        "change": '+0.5%',
        "chain": 'ETH',
        'vote':2400750,
        'watchlist': false
    }}
]